version: '2.1'
orbs:
  node: circleci/node@5.0.3
  terraform: circleci/terraform@3.2.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm --version
      - run: ls -l
      - persist_to_workspace:
          root: .
          paths:
            - terraform/*
  deploy:
    executor:
      name: terraform/default
      tag: 1.3.5
    environment:
      TF_IN_AUTOMATION: true
      GOOGLE_APPLICATION_CREDENTIALS: ./terraform-deploy.json
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: gcp auth
          command: echo $GCP_SERVICE_KEY_DEV > ./terraform/terraform-deploy.json
      - run: ls -l
      - run: cat ./terraform/terraform-deploy.json
      - terraform/init:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/plan:
          path: ./terraform
          var: google_project_id=$GOOGLE_PROJECT_ID,google_region=us-central1
      - terraform/apply:
          path: ./terraform
          var: google_project_id=$GOOGLE_PROJECT_ID,google_region=us-central1

workflows:
  deploy:
    jobs:
      - build
      - deploy:
          context: GCP
          requires:
            - build

