version: '2.1'
orbs:
  node: circleci/node@5.0.3
  terraform: circleci/terraform@3.2.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm --version
      - run: ls -l
      - persist_to_workspace:
          root: .
          paths:
            - terraform/*
  deploy:
    executor:
      name: terraform/default
      tag: 1.3.5
    environment:
      TF_IN_AUTOMATION: true
      GOOGLE_APPLICATION_CREDENTIALS: ./terraform-deploy.json
      TF_PARAM_VAR_FILE: ./terraform-vars.tfvars
      TF_PARAM_BACKEND_CONFIG: bucket=gcf-terraform-state
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: gcp auth
          command: echo $GCP_SERVICE_KEY_DEV > ./terraform/terraform-deploy.json
      - run: >
          echo "google_project_id=$GOOGLE_PROJECT_ID" > ./terraform-vars.tfvars
          echo "google_region=us-central1" > ./terraform-vars.tfvars
      - run: ls -l
      - run: cat ./terraform-vars.tfvars
      - terraform/init:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/plan:
          path: ./terraform
      - terraform/apply:
          path: ./terraform

workflows:
  deploy:
    jobs:
      - build
      - deploy:
          context: GCP
          requires:
            - build

