version: '2.1'
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  serverless-framework: circleci/serverless-framework@2.0
jobs:
  deploy:
    executor:
      name: serverless-framework/default
      python-version: 3.7-node
    steps:
      - checkout
      - gcp-cli/install
      - run:
          command: echo "$(cat /home/circleci/gcloud-service-key.json)"
          name: echo
      - run:
          command: >
            # Store service account

            echo "$<<parameters.gcloud-service-key>>" | base64 --decode >
            ${HOME}/gcloud-service-key.json


            # Initialize gcloud CLI

            gcloud --quiet config set core/disable_usage_reporting true

            gcloud --quiet config set component_manager/disable_update_check true

            gcloud auth activate-service-account
            --key-file=${HOME}/gcloud-service-key.json

            gcloud --quiet config set project $<<parameters.google-project-id>>


            if [[ -n $<<parameters.google-compute-zone>> ]]; then
              gcloud --quiet config set compute/zone $<<parameters.google-compute-zone>>
            fi


            if [[ -n $<<parameters.google-compute-region>> ]]; then
              gcloud --quiet config set compute/region $<<parameters.google-compute-region>>
            fi
          name: Initialize gcloud CLI to connect to Google Cloud
      - serverless-framework/setup
      - run:
          command: serverless deploy --verbose
          name: deploy
workflows:
  deploy:
    jobs:
      - deploy
