version: '2.1'
orbs:
  python: circleci/python@2.1.1
  gcp-cli: circleci/gcp-cli@2.4.1
  serverless-framework: circleci/serverless-framework@2.0
jobs:
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - python/install-packages
      - gcp-cli/install
      - gcp-cli/initialize
      - serverless-framework/setup
      - run:
          command: serverless deploy --verbose
          name: deploy
workflows:
  deploy:
    jobs:
      - deploy
