version: '2.1'
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  node: circleci/node@5.0.3
  terraform: circleci/terraform@3.2.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm --version
      - run: ls -l
      - persist_to_workspace:
          root: .
          paths:
            - terraform/*
  deploy:
    executor:
      name: gcp-cli/default
    environment:
      TF_IN_AUTOMATION: true
      GOOGLE_APPLICATION_CREDENTIALS: ./terraform-deploy.json
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: gcp auth
          command: echo $GCP_SERVICE_KEY_DEV > ./terraform-deploy.json
#      - gcp-cli/install
#      - run:
#          command: echo "$(cat /home/circleci/gcloud-service-key.json)"
#          name: echo
#      - gcp-cli/initialize:
#          gcloud-service-key: GCP_SERVICE_KEY_DEV
#          google-project-id: GOOGLE_PROJECT_ID
#      - run: export GOOGLE_APPLICATION_CREDENTIALS=/home/circleci/gcloud-service-key.json
      - run: ls -l
      - run: echo ./terraform-deploy.json
      - terraform/install:
          terraform_version: 1.3.5
      - terraform/init:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/fmt:
          path: ./terraform
      - terraform/plan:
          path: ./terraform

workflows:
  deploy:
    jobs:
      - build
      - deploy:
          context: GCP
          requires:
            - build

