version: '2.1'
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  node: circleci/node@5.0.3
  serverless-framework: circleci/serverless-framework@2.0
jobs:
  deploy:
    executor:
      name: serverless-framework/default
      python-version: 3.7-node
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - gcp-cli/install
      - run:
          command: echo "$(cat /home/circleci/gcloud-service-key.json)"
          name: echo
      - run:
          command: >
            # Store service account

            echo "$GCLOUD_SERVICE_KEY" | base64 --decode >
            ${HOME}/gcloud-service-key.json


            # Initialize gcloud CLI

            gcloud --quiet config set core/disable_usage_reporting true

            gcloud --quiet config set component_manager/disable_update_check true

            gcloud auth activate-service-account
            --key-file=${HOME}/gcloud-service-key.json

            gcloud --quiet config set project $GOOGLE_PROJECT_ID

          name: Initialize gcloud CLI to connect to Google Cloud
      - serverless-framework/setup
      - run: npm install
      - run:
          command: serverless deploy -v
          name: deploy
workflows:
  deploy:
    jobs:
      - deploy
