version: '2.1'
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  node: circleci/node@5.0.3
  terraform: circleci/terraform@3.2.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm --version
      - run: ls -l
      - persist_to_workspace:
          root: .
          paths:
            - terraform/function-source.zip
  deploy:
    executor:
      name: terraform/default
    steps:
      - attach_workspace:
          at: ./
      - run: ls -l
      - node/install:
          node-version: '16.13'
      - run: node --version
      - gcp-cli/install
      - run:
          command: echo "$(cat /home/circleci/gcloud-service-key.json)"
          name: echo
      - gcp-cli/initialize:
          gcloud-service-key: GCP_SERVICE_KEY_DEV
          google-project-id: GOOGLE_PROJECT_ID
      - terraform/install
      - terraform/init:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/fmt:
          path: ./terraform
      - terraform/plan:
          path: ./terraform

workflows:
  deploy:
    jobs:
      - build
      - deploy:
          context: GCP
          requires:
            - build

