version: '2.1'
orbs:
  node: circleci/node@5.0.3
  gcp-cli: circleci/gcp-cli@2.4.1
jobs:
  build-profile-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run: mkdir ./profile-service
      - run: mv -v src/apps/profile/* ./profile-service
      - persist_to_workspace:
          root: ./
          paths:
            - ./profile-service/*

  gcp-deploy-profile-service:
    executor:
      name: gcp-cli/google
    steps:
      - attach_workspace:
          at: ./
      - gcp-cli/initialize:
          gcloud-service-key: GCP_SERVICE_KEY_DEV
          google-project-id: GOOGLE_PROJECT_ID
      - run: |
          gcloud functions deploy profile-service-$CIRCLE_BRANCH \
            --gen2
            --region=us-central1 \
            --runtime=nodejs16 \
            --source=./profile-service/ \
            --entry-point=profile \
            --trigger-http

workflows:
  deploy:
    jobs:
      - build-profile-service
      - gcp-deploy-profile-service:
          context: GCP
          requires:
            - build-profile-service
          filters:
            branches:
              only:
                - main
                - gcp-functions
                - dev

