version: '2.1'
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  node: circleci/node@5.0.3
  terraform: circleci/terraform@3.2.0
jobs:
  deploy:
    executor:
      name: terraform/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - gcp-cli/install
      - run:
          command: echo "$(cat /home/circleci/gcloud-service-key.json)"
          name: echo
      - run:
          command: >
            # Store service account

            echo "$GCP_SERVICE_KEY_DEV" >
            ${HOME}/gcloud-service-key.json


            # Initialize gcloud CLI

            gcloud --quiet config set core/disable_usage_reporting true

            gcloud --quiet config set component_manager/disable_update_check true

            gcloud auth activate-service-account
            --key-file=${HOME}/gcloud-service-key.json

            gcloud --quiet config set project "$GOOGLE_PROJECT_ID"

          name: Initialize gcloud CLI to connect to Google Cloud
      - terraform/install
      - terraform/init:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/fmt:
          path: ./terraform
      - terraform/plan:
          path: ./terraform
workflows:
  deploy:
    jobs:
      - deploy:
          context: GCP
