version: '2.1'
orbs:
  node: circleci/node@5.0.3
  gcp-cli: circleci/gcp-cli@2.4.1
jobs:
  build-profile-service:
    executor:
      name: node/default
    steps:
      - checkout
      - run: (cd src/apps/profile && zip -r - .) > terraform/profile-service-source.zip
      - run: mkdir ./profile-service
      - run: mv -v src/apps/profile/* ./profile-service
      - persist_to_workspace:
          root: ./
          paths:
            - ./profile-service/*

  gcp-deploy-profile-service:
    executor:
      name: gcp-cli/google
    steps:
      - attach_workspace:
          at: ./profile-service/
      - gcp-cli/initialize:
          gcloud-service-key: $GCP_SERVICE_KEY_DEV
          google-project-id: $GOOGLE_PROJECT_ID
      - run: ls -l
      - run: |
          gcloud functions deploy profile-service-function \
            --region=us-central1 \
            --runtime=nodejs16 \
            --source=. \
            --entry-point=profile \
            --trigger-http

workflows:
  deploy:
    jobs:
      - build-profile-service
      - gcp-deploy-profile-service:
          context: GCP
          requires:
            - build-profile-service

