version: '2.1'
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  serverless-framework: circleci/serverless-framework@2.0
jobs:
  deploy:
    executor:
      name: serverless-framework/default
      python-version: 3.7-node
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - serverless-framework/setup
      - run:
          command: serverless deploy --verbose
          name: deploy
workflows:
  deploy:
    jobs:
      - deploy
